apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inventory-blue
  namespace: argocd
spec:
  project: inventory-project
  source:
    repoURL: 'https://github.com/KubeStock-DevOps-project/Dilan-WSO2-Final-Project-Inventory-Stock-Management-Microservices-System'
    targetRevision: HEAD
    path: k8s/overlays/blue
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: inventory
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
