apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/services/inventory-service
  - ../../base/services/order-service
  - ../../base/services/product-catalog-service
  - ../../base/services/supplier-service
namespace: inventory
commonLabels:
  track: blue
